# Generated by Django 4.2.6 on 2023-10-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
