# Generated by Django 4.2.6 on 2023-10-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
